### ISSUE TITLE
Why the abs layer in HyperpriorAnalysis is commented out? 

### ISSUE THREAD

**Issue by ZhangYuef** [Justin-Tan/high-fidelity-generative-compression#15]
https://github.com/Justin-Tan/high-fidelity-generative-compression/blob/2bd710c433fa73602afba9842561fe0a2840c7fe/src/network/hyper.py#L58

As the original paper adds this abs layer in HyperpriorAnalysis module, I am wondering if there is a particular reason to choose to comment this line out.

Thanks for the explanation in advance.

**Comment by Justin-Tan** [comment]
Hi,

IMO that part in the paper (Fig. 4, [1]) is a bit strange because the quantized latents $y$ can assume negative values as well, given that they're shifted to have zero mean and have non-negligible variance in general. 

I checked the tf compression repo and they don't put the abs there either [2], but let me know if you think of a good reason why it should be there. 

[1]: https://arxiv.org/abs/1802.01436
[2]: https://github.com/tensorflow/compression/blob/master/models/bmshj2018.py#L136

Cheers

**Comment by ZhangYuef** [comment]
Thanks for the reply! Your answer makes sense for me. I don't know why they put this `abs` layer in the paper either.

**Comment by ZhangYuef** [comment]
Hi @Justin-Tan , after checking tf compression repo's code I find that they do add a absolute operation on `y` before put it into `hyper_analysis_transform`. 
```python
  # Build autoencoder and hyperprior.
  y = analysis_transform(x)
  z = hyper_analysis_transform(abs(y))
```

Check the code [here](https://github.com/tensorflow/compression/blob/cf96d1b28e2e8d14f50ee0c7e6b6987ab010fdcd/models/bmshj2018.py#L231).
