### ISSUE TITLE
How to reproduce TensorFlow results?

### ISSUE THREAD

**Issue by Artem531** [Justin-Tan/high-fidelity-generative-compression#21]
Hi!

Thanks for your implementation of HiFiC!
I'm trying to understand why the results of this Pytorch implementation are so much different from the TensorFlow implementation. Are there any differences in implementations? How to reproduce TensorFlow results?
There are some examples below.

Thanks in advance for your reply

# Original
![kodim01 (1)](https://user-images.githubusercontent.com/40889390/107891875-706a6180-6f32-11eb-8bed-5e9cdaec910a.png)

# (low) Paper 
![kodim01](https://user-images.githubusercontent.com/40889390/107891493-094bad80-6f30-11eb-80d7-ec7dc5410bbf.png)

# (low) TensorFlow
![kodim01-0_258bpp](https://user-images.githubusercontent.com/40889390/107891532-43b54a80-6f30-11eb-92e9-c6bfa9c6847e.png)

# (low) Pytorch (Your pre-trained GAN model)
![kodim01_RECON_0_205bpp](https://user-images.githubusercontent.com/40889390/107891552-73fce900-6f30-11eb-95f8-82cc485596d4.png)

# (low) Pytorch (What I get when train Pytorch model with default settings and batch_size=12 for GAN)
![kodi01_RECON_0_214bpp](https://user-images.githubusercontent.com/40889390/107891578-9ee73d00-6f30-11eb-8d80-a9b0c7ff1972.png)

**Comment by Justin-Tan** [comment]
Thanks for bringing this up. The main difference would be that I trained for around 72 hours on a single GPU, which totals around 200k optimization steps, depending on the type of GPU. In the [HIFIC paper](https://arxiv.org/pdf/2006.09965.pdf), Appendix A.6, they state they trained for 2M optimization steps, 10x longer. I guess if you were willing to train for longer you would be able to obtain better results. To the best of my knowledge, all hyperparameters and the architecture is identical to the HIFIC paper and the Hyperprior implementation in [Balle et. al. (2018)](https://arxiv.org/abs/1802.01436) - with the one exception of the 'synthesis' transformations used in the Hyperprior and Generator.

As you may see in the definition of the [synthesis and hyper-synthesis transforms here](https://github.com/tensorflow/compression/blob/master/models/bmshj2018.py), instead of performing the standard cross-correlation during upsampling, they perform a true convolution. You can find the [implementation details here](https://github.com/tensorflow/compression/blob/master/tensorflow_compression/python/layers/signal_conv.py) - they use a custom Convolution class. I can't find any explanation why this is done - the docs in the TF Compression library claim this results in a speed increase, but I'm not sure how it affects the final result. If you find a good explanation of the point, I would be interested in hearing it. 

Also PRs to implement this are very welcome.

**Comment by Artem531** [comment]
Ok, thank you for your reply!
I will try to train the model with half-precision with my custom multi-GPU mode and check your guess.

I am closing this issue.

**Comment by mmSir** [comment]
@Artem531 Hi, Artem531! 
Have u tried to train more steps (for instance, 500k steps or more) yet? Could u please share your training results? 
I'd like to know whether this pytorch implementation could archive exactly the same result in HiFiC paper.
Here is my test result on CLIC2020 (12 images were removed due to out of memory during compress on my GPU)
![image](https://user-images.githubusercontent.com/35763352/113561469-3ca8df80-9637-11eb-820d-20324b5a6da1.png)


Thank you!

**Comment by Artem531** [comment]
@mmSir Hi, mmSir!

I tried to use 16-bit precision with apex (amp_level='O2') and find out that learning with these settings is not stable after ~25 epochs (300k steps (?)). So I could not reproduce the results :(

If you have multiple GPUs, you can try to use my Lightning PyTorch version of this repository for multi-GPU learning without 16-bit precision and apex   (https://github.com/Artem531/Lightning_HiFiC). But be careful I did not have much time to find all possible issues.

**Comment by mmSir** [comment]
All right. Thanks for your reply! :)
